[package]
name = "city-build-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
crossterm = "0.28.1"
rand = "0.8.5"
rand_distr = "0.4.3"
ratatui = { version = "0.28.1", features = ["unstable-widget-ref"] }
